- by: xpath
  locator: '//*[@text="姓名　"]/../*[@text="必填"]'
  action: send
  value: "{value}"

- by: xpath
  locator: '//*[@text="男"]'
  action: click

- by: xpath
  locator: '//*[@text="女"]'
  action: click

- by: xpath
  locator: '//*[@text="手机号"]'
  action: send
  value: "{phonenumber}"

- by: xpath
  locator: '//*[@text="保存"]'
  action: click